# Generated by Django 3.0.7 on 2020-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_form_class',
            name='Batting_Team',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='Bowling_Team',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='overs',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='runs',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='runs_last_5',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='wickets',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='input_form_class',
            name='wickets_last_5',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
